import { ThuDetails } from 'src/app/models/thu-details';
import { SelectionOption } from '../../models/selection-option.model';
import { PlanningType, ServiceLevel, TransportType } from '../../models/network-form.model';

export const SERVICE_LEVEL_OPTIONS: SelectionOption<ServiceLevel>[] = [
  {
    text: 'Standard Inbound',
    value: 'STD_INB',
  },
  {
    text: 'Closed Loop',
    value: 'CLOSED_LOOP',
  },
];
export const TRANSPORT_TYPE_OPTIONS: SelectionOption<TransportType>[] = [
  {
    text: 'FCL',
    value: 'FCL',
  },
  {
    text: 'FTL',
    value: 'FTL',
  },
  {
    text: 'LCL',
    value: 'LCL',
  },
  {
    text: 'LTL',
    value: 'LTL',
  },
  {
    text: 'MIX',
    value: 'MIX',
  },
];

export const PLANNING_TYPE_OPTIONS: SelectionOption<PlanningType>[] = [
  {
    text: 'Express',
    value: 'EXPRESS',
  },
  {
    text: 'Inbound',
    value: 'INBOUND',
  },
  {
    text: 'Outbound',
    value: 'OUTBOUND',
  },
];

export const NEW_XTR: any = {
  details: {
    consignee: {},
    consignor: {},
    involvedParties: [],
    otmTransmissionAcks: [],
    advancedShippingNotices: [],
    shipFrom: {
      address: {},
    },
    shipTo: {
      category: 'UNLOADING_POINT',
    },
    transportNetwork: {
      valid: true,
    },
    shipUnitLines: [],
    orderReleaseLines: [],
    transportBookings: [],
    tbrType: 'EXPRESS',
    expressType: 'NORMAL',
    orderType: 'TBR',
    shipitStatus: 'CREATED',
    shipitStatusType: 'DRAFT',
    qualifiersTBR: [],
    calloffMode: false,
    totals: {
      totalCount: 0,
      totalVolume: 0,
      totalWeight: 0,
    },
  },
  status: 'NEW',
};

export const NEW_PI: ThuDetails = {
  type: '',
  partWeight: 0,
  weightUom: 'KG',
  dimensionUom: 'MM',
  width: 0,
  height: 0,
  length: 0,
  partQuantity: 0,
  loadingDirection: 'ANY',
  packInstructionNumber: '',
  description: '',
  stackable: false,
  baseThuId: '',
  thuId: '',
  volume: 0,
  volumeUom: 'M3',
  packInstructionMaterials: [
    {
      oldMaterialNumber: '',
      materialDescription: '',
      materialNumber: '',
      imageUri: '',
      unitOfMeasure: '',
      key: '',
      iconName: '',
      thuId: '',
      width: 0,
      height: 0,
      length: 0,
      accountNumber: '',
      materialType: '',
      dimensionUom: 'MM',
      grossWeight: 0,
      baseUom: '',
      weightUom: 'KG',
      layerTotal: 0,
      packInstructionKey: '0001',
      packInstructionItem: 1,
      customerNumber: '',
      parent: '',
      quantityPerLayer: 1,
      numberOfLayers: 1,
      originalNumberOfLayers: 1,
      partNumber: '',
      displayMode: false,
      partQuantity: 0,
      containsPart: true,
      iconType: '',
      edit: false,
      layerEnabled: false,
      outErp: true,
      locked: false,
      itemNumberOfSoDocument: 0,
      quantityEnabled: false,
      subHuIndicator: false,
      layerVariable: false,
      itemType: '',
      thuFlag: false,
      volume: 0,
      volumeUom: 'M3',
      typeText: '',
      dynamicCallOff: false,
      flexibleUnitLoad: false,
      mode: '',
    },
  ],
  altPackInstructionNumber: '',
  consignee: '',
  consigneeName: '',
  consignorName: '',
  customerNumber2: '',
  dimensionOverRide: false,
  dynamicCallOff: false,
  flexibleUnitLoad: false,
  grossWeight: 0,
  internalText: '',
  lastCheck: '',
  longText: '',
  minimumQuantity: 0,
  oldPackInstructionNumber: '',
  packRefCode: '',
  parmaList: [],
  partContainerGrossWeight: 0,
  partContainerUnitload: 0,
  partNumber: '',
  recordCreatedBy: '',
  recordCreatedDate: null,
  recordLastChangeBy: '',
  recordLastChangeDate: null,
  shipFrom: '',
  status: '',
  subHuGrossWeight: 0,
  subMaterial: '',
  supplierConfirmedBy: '',
  supplierConfirmedDate: null,
  thuFlag: false,
  transferKey: '',
  unloadingPoint: '',
  validFromDate: null,
  validToDate: null,
};
